
spring:
  datasource:
    url: jdbc:mysql://rm-wz9hsmiyn0xe3b9m0.mysql.rds.aliyuncs.com:3306/haircut?useUnicode=yes&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: haircut
    password: ZXCasd123
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 172.18.197.78
    port: 6379
    password: 666666
    timeout: 3600ms #超时时间
    lettuce:
      pool:
        max-active: 8 #最大连接数
        max-idle: 8 #最大空闲连接 默认8
        max-wait: -1ms #默认-1 最大连接阻塞等待时间
        min-idle: 0 #最小空闲连接
  rabbitmq:
    host: 172.18.197.78
    port: 5672
    username: root
    password: 666666

files-location: /files
host-url: https://api.ydqmf.com
server:
  port: 80
